spring:
  application.name: sc-shipping-service # for config server and service-registry
  cloud:
    stream:
      bindings:
        shipOrder-in-0:
          destination: order-shipping-queue
        shipOrder-out-0:
          destination: order-delivered-queue
      servicebus.queue.bindings:
        shipOrder-in-0.consumer.checkpoint-mode: MANUAL
        shipOrder-out-0.consumer.checkpoint-mode: MANUAL
    azure.servicebus.connection-string:
shipping.duration: 0
