spring:
  jpa.hibernate.ddl-auto: update
  application.name: sc-order-service # for config server and service-registry
  cloud.loadbalancer.ribbon.enabled: false
  jms.servicebus:
    connection-string:
order:
  delivered-queue-name:
  shipping-queue-name:
  products-api-url: